Refactory of PR #13
GDSC-DEU/Blog-API pull request #14
Opened 2023-07-14 07:46 UTC by thelight0804

#13 에서 코드 리뷰 내용 바탕으로 리펙토링 진행했습니다

2023-07-14 07:47 UTC, thelight0804 commented
PR 한 번 하면 이때까지 브랜치에 커밋했던 모든 게 한꺼번에 올라가네요..
커밋마다 PR 생성하고 싶으면 그때 PR을 생성해야 하나요?

2023-07-14 07:48 UTC, thelight0804 commented
> PR 한 번 하면 이때까지 브랜치에 커밋했던 모든 게 한꺼번에 올라가네요.. 커밋마다 PR 생성하고 싶으면 그때 PR을 생성해야 하나요?

ㅁㅁㅁ

2023-07-17 01:43 UTC, Mina-1316 requested changes
일단은 게시글 쪽만 리뷰 했읍니다...

2023-07-17 01:43 UTC, Mina-1316 commented on src/main/java/com/gdsc/blog/article/service/ArticleService.java
> +        articles.forEach(article -> articleList.add(articleMapper.toDto(article)));
이 부분도, +69~+70 부분의 리뷰를 참고하여 고쳐 주시기 바랍니다.

2023-07-17 01:43 UTC, Mina-1316 commented on src/main/java/com/gdsc/blog/article/service/ArticleService.java
> +        }
이 부분도 전에 리뷰했던 것처럼 `Optional.orElseThrow()` 메소드를 활용해 주시면 좋을 거 같습니다.

```suggestion
        return articleRepository.findById(idx).orElseThrow(() -> new IllegalArgumentException("Not found Article by ID"));
```

2023-07-17 01:43 UTC, Mina-1316 commented on src/main/java/com/gdsc/blog/article/service/ArticleService.java
> +     * @return Article 객체
각 파라미터에 대한 조금 더 자세한 설명이 들어가면 좋을 듯 합니다!
또, 던져지는 예외에 대한 설명도 작성되면 좋을 거 같습니다.

```suggestion
     * @param user 게시글 수정 요청 사용자
     * @return Article 수정된 게시글 내용을 담고 있는 객체
     * @throws IllegalArgumentException 게시글 작성자와 로그인한 유저가 같지 않을 시
     * @throws NoSuchElementException 게시글 또는 유저를 찾을 수 없을 시
```

2023-07-17 01:43 UTC, Mina-1316 commented on src/main/java/com/gdsc/blog/article/service/ArticleService.java
> +        User user = userRepository.findByUsername(username).orElseThrow(); //유저 정보 가져오기
`username`을 통해 유저를 검색하는 이유가, 유저가 존재하는지 혹은 존재하지 않는지를 파악하기 위해서인가요?

이미 있는 username이라는 정보를 위해 쿼리를 한번 더 날리는게 성능상/가독성 면에서 전혀 이점이 되고 있지 못하는 거 같아요...

2023-07-17 01:43 UTC, Mina-1316 commented on src/main/generated/com/gdsc/blog/mapper/ArticleMapperImpl.java
Generated 코드가 깃으로 올라오면 곤란한데... 이거는 실수로 올라온 건지 확인이 필요할 거 같네요

2023-07-17 01:43 UTC, Mina-1316 commented on src/main/java/com/gdsc/blog/configuration/SecurityConfig.java
> +        http.csrf(AbstractHttpConfigurer::disable);
CSRF는 Production 환경에서는 켜져 있는 게 좋을 거 같은데...스위칭이 가능하게 구현되면 좋을 거 같습니다

2023-07-17 01:43 UTC, Mina-1316 commented on src/main/java/com/gdsc/blog/mapper/ArticleMapper.java
> +    ArticleMapper INSTANCE = Mappers.getMapper(ArticleMapper.class);
스프링 DI가 이미 해당 매퍼를 IOC 컨테이너에 집어넣어준 상태이기 때문에 이 INSTANCE 스태틱 변수를 굳이 사용할 이유는 없어 보입니다!

2023-07-17 01:43 UTC, Mina-1316 commented on src/main/java/com/gdsc/blog/security/MyUserDetails.java
> +        }
이 부분에서, `optional.get()`은 데이터를 반환하고 없거나 null일 경우 `NoSuchElement`를 throw하기 때문에, 아래의 if문이 절대로 동작하지 않게 됩니다.

https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#get--

따라서, 의도하고자 하는 동작을 위해서는 `.orElse(null)` 혹은 `.orElseThrow()` 메소드를 사용해야 합니다.
```suggestion
        // Example 1(추천 안함)
        final User user = userRepository.findByUsername(username).orElse(null);
        if (user == null) {
            throw new UsernameNotFoundException("User '" + username + "' not found");
        }
        // Example 2
        final User user = userRepository.findByUsername(username).orElseThrow(() ->
            new UsernameNotFoundException("User '" + username + "' not found"));
       
```

2023-07-17 01:43 UTC, Mina-1316 commented on src/main/java/com/gdsc/blog/security/jwt/JwtTokenFilter.java
> +            httpServletResponse.sendError(HttpServletResponse.SC_BAD_REQUEST, ex.getMessage());
필터가 실패했을 경우 bad request보다는 unauthorised 혹은 forbidden이 HTTP 코드 상 조금 더 전하고자 하는 바에 일치하지 않을까 싶습니다!

2023-07-17 09:03 UTC, Mina-1316 commented on src/main/java/com/gdsc/blog/article/service/ArticleService.java
> +        articles.forEach(article -> articleList.add(articleMapper.toDto(article)));
```java
    private void grow(int minCapacity) {
        // overflow-conscious code
        int oldCapacity = elementData.length;
        int newCapacity = oldCapacity + (oldCapacity >> 1);
        if (newCapacity - minCapacity < 0)
            newCapacity = minCapacity;
        if (newCapacity - MAX_ARRAY_SIZE > 0)
            newCapacity = hugeCapacity(minCapacity);
        // minCapacity is usually close to size, so this is a win:
        elementData = Arrays.copyOf(elementData, newCapacity);
    }
```
 해당 사례에 대한 참고 자료입니다! ArrayList의 사이즈 증가 메소드에요

2023-08-08 16:29 UTC, cmsong111 commented on src/main/java/com/gdsc/blog/configuration/SecurityConfig.java
> +        http.csrf(AbstractHttpConfigurer::disable);
JWT 토큰을 이용하여 서비스를 이용하는 부분에선 CSRF를 비활성화 하는 게 맞다고 알고 있습니다.

제가 잘못 알고있는 부분일까요?

2023-08-08 16:43 UTC, merged